/**
 * This file was generated by cantools version 35.3.0 Tue Oct 27 17:02:05 2020.
 */

#include <string>
#include <iostream>
#include <algorithm>
#include <sstream>

#ifndef canmodule_H
#define canmodule_H


class CAN_example_message{
    public:
        /**
        * True/False
        */
        bool enable;

        /**
        * Range: 0..50 (0..5 m)
        * Scale: 0.1
        */
        float average_radius;

        /**
        * Range:229.52..270.47 degK
        * Scale: 0.01
        */
        float temperature;

        bool enable_set,average_radius_set,temperature_set;

        CAN_example_message();

        void setEnable(std::string);
        void setRadius(std::string);
        void setTemp(std::string);
        void reset();
        const char* encodeForPipe();
        bool messageReady();
        void decodeFromPipe(const char*);
        //std::string values_keywords[3] = {"Enable","AverageRadius","Temperature"};
        //void parse_message(std::string message);
};


#endif
