/**
 * This file was generated by cantools version 35.3.0 Tue Oct 27 17:02:05 2020.
 */

#include <string>
#include <iostream>
#include <algorithm>
#include <sstream>
#include <boost/lexical_cast.hpp>

#ifndef canmodule_H
#define canmodule_H


class CAN_example_message{
    public:
        /**
        * True/False
        */
        bool switch_value;

        /**
        * Range: 0..50 (0..5 m)
        * Scale: 0.1
        */
        float average_radius;

        /**
        * Range:229.52..270.47 degK
        * Scale: 0.01
        */
        float temperature;

        CAN_example_message();

        void reset();
        const char* encodeForPipe();
        void decodeFromPipe(const char*);
        void addMessageLine(std::string);
        bool messageReady();

    private:
        bool switch_value_set,average_radius_set,temperature_set;
        void setSwitchValue(std::string);
        void setRadius(std::string);
        void setTemp(std::string);
};


#endif
